-d /home/lpnm/Documents/Electronica/Sipeed/Tang_Nano_20K/SPRAM_LED_Blink_test/impl/gwsynthesis/SPRAM_LED_Blink_test.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/lpnm/Documents/Electronica/Sipeed/Tang_Nano_20K/SPRAM_LED_Blink_test/src/spram_led.cst
-cfg /home/lpnm/Documents/Electronica/Sipeed/Tang_Nano_20K/SPRAM_LED_Blink_test/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
